version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    links:
      - postgresql
    volumes:
      - ./web:/code
    env_file: .env
    command:
      ./manage.py run --host 0.0.0.0 --debugger --reload

  postgresql:
    build: ./postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=postgres
